spring.security.oauth2.client.registration.google.client-id=942810230032-s2eb85qi3k72uhc6nom6jb327ltktv56.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email
